gitGraph BT:
    commit id: "Initial commit"
    branch develop
    commit id: "WIP: Restyle footer"
    commit id: "WIP: Restyle footer part 2: The Lost World"
    commit id: "Restyle footer complete"
    commit id: "Restyle header"